language: node_js
node_js: "10"
sudo: false
install: true
jdk: oraclejdk11
dist: trusty
script:
  - mvn clean package

cache:
  yarn: true
  directories:
    - $HOME/.m2/repository

notifications:
  email: false
  webhooks:
    urls:
      - secure: "HugjGQzANUh3n5AM0/ASUfGbxRWOJmq0FnyUkIHlA4EXDzKVLoaML1HA7eU6ueMSVRRQ5ExkKTrwY+vcEFaMRyrpIxdeAnmWxKQve8qSORyyB8YIQaI8KkCLCHSLxYkGbGexIESuXtxtHY+fWFHLfWUIXHR6XQs2321GJbkaqJfhO9mC0Z4bK3YAPR2DJrIVU0uZwfY728+PPGFvzZRAFbN3m6Yg/Mtju3gxNByAh8nRUS/zVH0Jww6OpDpZ8T5kiiRnzYiF9Ea/EvzMC1+tPxntRx6M48I+bzmNS7T7bTO+nEHgd6cpWJA3PDbiaEA8Vvks+ukFmgTRYX76bAuaXR6yXP5z1mKgNUqotB1ANGsx5Od5RHgSpD++XgctMhyl17tfFLk9hIqCphu96jPkuyAgvNYZHwnJ/2ZVDH+bPFEfZ9dzyUWMi4vzMz1MjAQVZo/ko8QimJcNgRED8LGaJeemtCuuosnt8ZKdy9PrjJgNA/BpgDL8dkwZCiz6ks8NxsbsFEXMGPN7NJvamC3Oe/FU3kv9b2RRgFge8OQm8zwGo079l82GZYrbtq6r0Fu1Tt7mWzEE5N6WgmwAWyydmkQkTxfFAPj/hJM0H+49VFE7khQsPexSwFxMsDTW7o7W0sOeKXpwI6KTW0BsUeG0JKvjICEb6Ap9nFVob2SC7CI="
    on_start: always
