language: node_js
node_js: "10"
sudo: false
install: true
jdk: oraclejdk11
dist: trusty
script:
  - mvn clean package

cache:
  yarn: true
  directories:
    - $HOME/.m2/repository

notifications:
  email: false
